### ISSUE TITLE
`ParseError: Unexpected token` if brfs is loaded before folderify

### ISSUE THREAD

**Issue by LoicMahieu** [parroit/folderify#5]
If `brfs` is loaded **after** `folderify`, it throws a `ParseError: Unexpected token` exception. If brfs is loaded before folderify, no problem.

Not so familiar with browserify transformers, I don't know how it can be solved.

```js
var browserify = require('browserify');
var fs = require('fs');

var b = browserify('./test.js');
b.transform('folderify');
b.transform('brfs');

b
  .bundle()
  .on('error', function (err) {
    console.error(err);
  })
  .pipe(fs.createWriteStream('bundle.js'));
```

An excetion is thrown:
```

./test.js:2
    folder = (function(){var self = {}fined,
                                      ^
ParseError: Unexpected token
```

**Comment by parroit** [comment]
Thank you for the report.

I added two test to devel branch to try to reproduce your problem, but they both pass.
Please see them [here](https://github.com/parroit/folderify/blob/devel/test/folderify_test.js#L92).
Could you try to run the tests and report if they failed for you?

It could also be useful if you can provide the content of your `./test.js` file.Thank you for the report.

I added two test to devel branch to try to reproduce your problem, but they both pass.
Please see them [here](https://github.com/parroit/folderify/blob/devel/test/folderify_test.js#L92).
Could you try to run the tests and report if they failed for you?

It could also be useful if you can provide the content of your `./test.js` file.

**Comment by LoicMahieu** [comment]
Thanks for response.

`./test.js`:
```js
var includeFolder = require('include-folder'),
    folder = includeFolder(".");
```

Tests in the devel branch looks like my example so I think the problem is solved. Thanks

**Comment by parroit** [comment]
you're welcome
