### ISSUE TITLE
falafel 0.3.1 and shrinkwrap

### ISSUE THREAD

**Issue by mdh-cc** [parroit/folderify#7]
Hi,

I'm using folderify 0.6.0 in my current project and have some problems with the falafel dependency.
Because of its `bundledDependency` (esprima) `npm shrinkwrap` produces an error (expected '*' but got '1.1.0-dev') in its latest versions.

Is it possible to update the falafel dependency where this kind of construct is no longer been used?

**Comment by parro-it** [comment]
Hi, I'm planning to release a new version soon, I'll upgrade version of all libraries for sure

**Comment by parroit** [comment]
Just published version 0.7.1 which depends on falafel ^1.2.0

**Comment by mdh-cc** [comment]
great, thanks
